-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. Create Table 'solicitacoes'
create table public.solicitacoes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome_cliente text not null,
  whatsapp text not null,
  arquivo_url text
);

-- Enable RLS
alter table public.solicitacoes enable row level security;

-- Policy: Allow Anon Insert (Public Submission)
create policy "Enable insert for anon users"
on public.solicitacoes
for insert
to anon
with check (true);

-- Policy: Allow Read for Authenticated/Anon (Since admin is client-side for now, but really should be secured. 
-- For this MVP, we might need to allow public read OR assume the admin page is behind some auth. 
-- Given the prompt implies simple setup:
create policy "Enable read for all"
on public.solicitacoes
for select
using (true);

-- 3. Create Table 'produtos'
create table public.produtos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric,
  image_url text
);

-- Enable RLS
alter table public.produtos enable row level security;

-- Policy: Allow Read for All (Public Storefront)
create policy "Enable read for all"
on public.produtos
for select
using (true);

-- Policy: Allow Anon Insert (For Seeding/Admin temporarily)
create policy "Enable insert for anon"
on public.produtos
for insert
with check (true);

-- 2. Create Storage Bucket 'receitas'
insert into storage.buckets (id, name, public) 
values ('receitas', 'receitas', true)
on conflict (id) do nothing;

-- Policy: Allow Upload for Anon
create policy "Allow Public Uploads" 
on storage.objects 
for insert 
to anon 
with check (bucket_id = 'receitas');

-- Policy: Allow Public Read (View Images)
create policy "Allow Public Select" 
on storage.objects 
for select 
to public 
using (bucket_id = 'receitas');
