-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. Create Table 'solicitacoes'
create table public.solicitacoes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome_cliente text not null,
  whatsapp text not null,
  arquivo_url text,
  status text default 'active'
);

-- Enable RLS
alter table public.solicitacoes enable row level security;

-- Policies for solicitacoes
create policy "Enable all for solicitacoes" on public.solicitacoes for all using (true) with check (true);

-- 3. Create Table 'produtos'
create table public.produtos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric,
  image_url text,
  display_order integer default 0
);

-- Enable RLS
alter table public.produtos enable row level security;

-- Policies for produtos
create policy "Enable all for produtos" on public.produtos for all using (true) with check (true);

-- 2. Create Storage Bucket 'receitas'
insert into storage.buckets (id, name, public) 
values ('receitas', 'receitas', true)
on conflict (id) do nothing;

-- Policy: Allow Upload for Anon
create policy "Allow Public Uploads" 
on storage.objects 
for insert 
to anon 
with check (bucket_id = 'receitas');

-- Policy: Allow Public Read (View Images)
create policy "Allow Public Select" 
on storage.objects 
for select 
to public 
using (bucket_id = 'receitas');
