-- Keep customer prescription files separate from the public `receitas` bucket,
-- which is also used by the storefront for public product images.
create table if not exists public.solicitacoes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  nome_cliente text not null,
  whatsapp text not null,
  arquivo_url text,
  status text default 'active',
  observacoes text
);

alter table public.solicitacoes add column if not exists observacoes text;
alter table public.solicitacoes enable row level security;

-- The browser can submit a request, but only the authenticated admin edge
-- function can read, update, or delete requests and their contact details.
drop policy if exists "Enable all for solicitacoes" on public.solicitacoes;
drop policy if exists "Enable insert for anon users" on public.solicitacoes;
drop policy if exists "Enable read for all" on public.solicitacoes;
drop policy if exists "Public can submit service requests" on public.solicitacoes;
create policy "Public can submit service requests"
  on public.solicitacoes
  for insert
  to anon, authenticated
  with check (
    length(trim(nome_cliente)) between 3 and 160
    and length(regexp_replace(coalesce(whatsapp, ''), '\D', '', 'g')) between 10 and 13
    and (status is null or status = 'active')
    and (arquivo_url is null or length(arquivo_url) <= 12000)
    and (observacoes is null or length(observacoes) <= 5000)
  );

revoke all on table public.solicitacoes from anon, authenticated;
grant insert (nome_cliente, whatsapp, arquivo_url, observacoes) on table public.solicitacoes to anon, authenticated;
grant all on table public.solicitacoes to service_role;
grant usage, select on sequence public.solicitacoes_id_seq to anon, authenticated;
grant usage, select on sequence public.solicitacoes_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'receitas-privadas',
  'receitas-privadas',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'application/pdf']::text[]
)
on conflict (id) do update
set name = excluded.name,
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can upload private prescription files" on storage.objects;
drop policy if exists "Public can read private prescription files" on storage.objects;
drop policy if exists "Authenticated users can read private prescription files" on storage.objects;
create policy "Public can upload private prescription files"
  on storage.objects
  for insert
  to anon, authenticated
  with check (
    bucket_id = 'receitas-privadas'
    and name ~ '^intake/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(jpg|jpeg|png|pdf)$'
  );

-- Intentionally no SELECT policy exists for this bucket. Admin reads are
-- provided by a short-lived signed URL from the session-validated edge function.
